# Includes one of the default files in src/bootstrap/defaults
profile = "compiler"
changelog-seen = 2

[build]
target = ["x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"]

[rust]
llvm-libunwind = 'in-tree'
musl-root = '/usr/local/musl'
debug = true